_target_: src.models.baby_module.BabyLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001

net:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: resnet18
  encoder_weights: imagenet
  in_channels: 1
  classes: 2

loss_func:
  _target_: torch.nn.CrossEntropyLoss
  weight:
    _target_: torch.Tensor
    data: [0.01, 0.99]
    


eval_img_path: ${paths.log_dir}/tmp

log_train_img: false
log_val_img: true
log_test_img: true