_target_: src.models.baby_segment_module.BabySegmentLitModule

optimizer: 
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  min_lr: 0.0001
lr_scheduler_monitor: "val/loss"

net:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 1
  classes: 2
  decoder_use_batchnorm: false

loss_func:
  _target_: torch.nn.CrossEntropyLoss
  weight:
    _target_: torch.Tensor
    data: [0.01, 0.99]
  label_smoothing: 0.01
    


eval_img_path: ${paths.log_dir}/tmp

log_train_img: false
log_val_img: true
log_test_img: true