_target_: src.models.baby_segment_module.BabySegmentLitModule

optimizer: 
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  min_lr: 0.0001
lr_scheduler_monitor: "val/loss"

net:
  _target_: segmentation_models_pytorch.Unet
  encoder_weights: imagenet
  in_channels: 1
  classes: 2
  decoder_use_batchnorm: false

loss_func:
  # _target_: segmentation_models_pytorch.losses.SoftBCEWithLogitsLoss
  
  # _target_: segmentation_models_pytorch.losses.MCCLoss

  # _target_: segmentation_models_pytorch.losses.JaccardLoss
  # mode: binary
  # log_loss: false
  # from_logits: false
  # smooth: 0.01

  # _target_: src.models.losses.DiceCECombined.DiceCECombined
  # ce_loss_weight:
  #   _target_: torch.Tensor
  #   data: [0.005, 0.995]
  
  _target_: torch.nn.CrossEntropyLoss
  weight:
    _target_: torch.Tensor
    data: [0.01, 0.99]
  label_smoothing: 0.01
    
postprocessor: null

eval_img_path: ${paths.log_dir}/tmp

log_train_img: 0.05
log_val_img: 0.5
log_test_img: 1.