# @package _global_

defaults:
  - _self_
  - datamodule: baby_segment.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: baby_segment_resnet50.yaml
  - logger: wandb.yaml
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/runs/2022-09-06_11-52-22/checkpoints/epoch_017.ckpt
# ckpt_path: ${paths.log_dir}/train/runs/2022-09-06_11-41-27/checkpoints/last.ckpt
