# @package _global_

defaults:
  - _self_
  - datamodule: baby.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: baby.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/runs/2022-08-21_08-47-24/checkpoints/last.ckpt
