defaults:
  - baby_segment.yaml

_target_: src.datamodules.baby_segment_localized_datamodule.BabySegmentLocalizedDataModule
loosen_amount: 0.5
padding_relative_to_label: true
resize_localized_region: [320, 544]